### ISSUE TITLE
Enemy Knight sword throw velocities are inconsistent.

### ISSUE THREAD

**Issue by Sebp23** [Sebp23/dont-run-with-swords#45]
# Steps to Reproduce:
1. Move to the main branch and open scene/level 2
1. Play through the level until you reach the Red Knight at the end.
1. Allow the knight to detect you by getting close enough (they will stop moving when they detect you)
1. Observe the speed of their sword throw
1. Now move to scene/level 3
1. Play through the level until you reach a red knight
1. Allow the knight to detect you by getting close enough
1. Observe the speed of their sword throw

# Results:
By following the steps above, the player will be able to see a great difference in the speed at which the knight throws their sword in each level. The Red Knight in level 2 throws their sword at a very high speed, while the Red Knights in level 3 throw their sword at a much slower speed, despite the velocity being set the same for both. The level 3 Red Knight sword speed is also inconsistent with itself, as sometimes, the sword is thrown at an even slower speed than before.

# Expected Results:
The Red Knights should all throw their swords at the same speed, no matter which level they're in, or where the player is positioned.

**Comment by dantogno** [comment]
@Sebp23  good writeup! Question: is either one throwing at the "correct" speed? If so which?
